name: databox

services:
  databox:
    container_name: databox-apache
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8091:8091"
    volumes:
      - ./cloud:/var/www/html
      - ./env.php:/var/www/env.php:ro
      - ./.env.development:/var/www/.env.development:ro
    environment:
      APP_ENV: development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
